name: FastAPI Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el proyecto
      uses: actions/checkout@v4

    - name: Instalando Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Instalando dependencias
      run: 
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: 
        pytest ./app/h2.py

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Iniciar sesión en Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Obtener la versión actual
      id: get_version
      run: echo "::set-output name=version::$(git describe --abbrev=0 --tags)"
    
    - name: Incrementar la versión
      id: increment_version
      run: echo "::set-output name=version::$(echo ${{ steps.get_version.outputs.version }} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
    
    - name: Construir y subir la imagen
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-docker:${{ steps.increment_version.outputs.version }} --push .

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
